### ISSUE TITLE
Etrade reports some (or all) ESPP lots under "Long term non-covered"

### ISSUE THREAD

**Issue by soumyadeep2007** [hickeng/financial#105]
## Expectation:

Etrade reports all ESPP lots under "Long term covered" in 1099-B.

## Reality:

Etrade reports some (or all) ESPP lots under "Long term non-covered" in 1099-B.

## Notes:

* All ESPP lots are "covered" securities and should be reported as so.
* The spreadsheet correctly lists them under "covered" and correctly recommends filing it under "Part II Box D"

## Possible resolutions:

* I have spoken to Etrade and they have passed on the request for an amended 1099-B. I will get back here if their team approves it.
* Regardless of whether we get an amended 1099-B from E-trade, we can simply file with these listed as Long term covered in 8949 under "Part II Box D".

**Comment by hickeng** [comment]
@soumyadeep2007 I'm not 100% sure about this, but I think you'll need to add code `T` to field `(f)` in the Form 8949. See [here](https://www.irs.gov/instructions/i8949#en_US_2022_publink59421zd0e1936:~:text=You%20received%20a%20Form%201099%2DB%20(or%20substitute%20statement)%20and%20the%20type%20of%20gain%20(or%20loss)%20shown%20in%20box%202%20is%20incorrect) for IRS instructions.

**Comment by soumyadeep2007** [comment]
> @soumyadeep2007 I'm not 100% sure about this, but I think you'll need to add code T to field (f) in the Form 8949. See [here](https://www.irs.gov/instructions/i8949#en_US_2022_publink59421zd0e1936:~:text=You%20received%20a%20Form%201099%2DB%20(or%20substitute%20statement)%20and%20the%20type%20of%20gain%20(or%20loss)%20shown%20in%20box%202%20is%20incorrect) for IRS instructions.

Sadly, there is no workflow I could find in Turbo Tax online to enter stuff that fills up code "T".

Wonder what would happen if I still just follow through with the regular workflow as if E-trade hadn't made that mistake (just report it with part ii box d).

**Comment by soumyadeep2007** [comment]
Okay so this is my attempt at figuring this out.

1. Quoting the 8949 instructions if "You received a Form 1099-B (or substitute statement) and the type of gain (or loss) shown in **box 2** is incorrect" we are supposed to enter "T" in (f).
2. There is no "box 2" in 1099-CONS_MSSB_LLC (1099-b from Etrade) file yields nothing.
3. "Box 2" appears in the form that is sent to the IRS directly from the broker (https://www.irs.gov/pub/irs-pdf/f1099b.pdf) -> see page 3.
4. So according to [here](https://www.irs.gov/instructions/i1099b#:~:text=purchased%2075%20shares.-,Box%202.%20Type%20of%20Gain%20or%20Loss,-Determine%20whether%20the), box 2 is the "type" of gain/loss reported by the broker.
"Determine whether the gain or loss is **short-term or long-term** under section 1222, and **whether any portion of the gain or loss is ordinary**."
      a. For me, Long term covered was mis-reported as Long term non-covered. Both are "Long term", so that should should be good.
      b. Under `FORM 1099-B TOTALS SUMMARY` under `LONG -TERM GAIN OR (LOSSES) - REPORT ON FORM 8949, PART II`, I have all 0s for any item with `Ordinary` such as `Box D - Ordinary - (basis reported to the IRS) ` etc. So my guess was for none of the lots was the ORDINARY  checked.
      c. Given i. and ii. above, I don't think the type they reported to the IRS changes in our case. **And we may not have to fill in "T" under column (f)**.

I will report back here if I see anything different on the amended 1099-b (if I ever do receive one)

**Comment by hickeng** [comment]
Thanks for the detail! If you just change the `Sales Section` to Long Term Covered, does that look right in the generated form?

Given the presence of that dropdown, I'm assuming we're allowed to change it when it's incorrect. Perhaps the act of changing it will generate an appropriate code for `(f`)... 🤷

**Comment by soumyadeep2007** [comment]
> Thanks for the detail! If you just change the `Sales Section` to Long Term Covered, does that look right in the generated form?

Unfortunately, I don't see a way to see the generated form. For that I have to finish my taxes and pay TurboTax right? (I'm using TT Online). **Do you know of a way to see the generated form earlier?**

> 
> Given the presence of that dropdown, I'm assuming we're allowed to change it when it's incorrect. Perhaps the act of changing it will generate an appropriate code for `(f`)... 🤷

Hmm interesting theory. For me last weekend when I tried import from E-trade it had said "No tax documents found". So, I had to manually enter each lot. Maybe I will retry the import and then change it from the drop-down.

**Comment by hickeng** [comment]
>  Do you know of a way to see the generated form earlier?

As part of figuring out entry into TT I bought the desktop version for this year and that let's me inspect the underlying worksheets and generated forms. I'll try a correction of this type when I get home tonight and see what it does.

**Comment by soumyadeep2007** [comment]
> > Do you know of a way to see the generated form earlier?
> 
> As part of figuring out entry into TT I bought the desktop version for this year and that let's me inspect the underlying worksheets and generated forms. I'll try a correction of this type when I get home tonight and see what it does.

Oh wow I didn't know that. Thank you from the bottom of my heart! :slightly_smiling_face:

**Comment by soumyadeep2007** [comment]
Hey @hickeng , no rush but did you get a chance to look at this?

Thanks again for all your help!

**Comment by hickeng** [comment]
@soumyadeep2007 i was trying to figure out where this conversation was last night! Went through multiple slack instances and gchat looking for it. Didn't check GitHub 🤦‍♂️

Tried it last night - there isn't a Sale Section in the form view of Desktop, but you can override the box to use. Unfortunately it had no effect when generating the form and my fractional Broadcom share continued to show up as Noncovered despite overriding to Box D.

If you do pay for online I strongly recommend confirming on the generated Form 8949 that it got placed in the desired section and raising an issue with TT if it's not moved over.

**Comment by soumyadeep2007** [comment]
> Tried it last night - there isn't a Sale Section in the form view of Desktop, but you can override the box to use. Unfortunately it had no effect when generating the form and my fractional Broadcom share continued to show up as Noncovered despite overriding to Box D.

Thank you so much for trying this out! Bummer, so buying the desktop version isn't going to work. I had to manually enter my lots anyway in TT online since TT import wasn't working for me last weekend. I can retry importing + changing the dropdown (to see if "T" materializes). Otherwise, I will just stick to the manual entry that I have, where I have re-classified the ESPP lots as long term covered and hope for the best.

There is another option, do a paper file from TT, download the form and manually enter "T" before filing. But that is cringy and TT has no record of what I'm doing and is a hassle for posterity.

**Comment by soumyadeep2007** [comment]
How much does "T" matter I wonder, if the lot is correctly classified with Part II Box D. I hope that the code doesn't change the tax calculation. What I think is that it is some kind of note to IRS that Etrade misclassified the lot. 🤷

**Comment by hickeng** [comment]
> How much does "T" matter I wonder, if the lot is correctly classified with Part II Box D. I hope that the code doesn't change the tax calculation. What I think is that it is some kind of note to IRS that Etrade misclassified the lot. 🤷 

No idea - I figure the same for an indication that it's the wrong type, but does type include covered vs non-covered or long vs short? Given the broker needs to report covered to the IRS themselves a covered sale incorrectly assigned to noncovered can't be completely addressed just with a change in your form.

I'm just as much in the dark as you for how to handle this one. The only correct answer I can see if a corrected 1099 from Etrade.
