### ISSUE TITLE
"Shares (FMV)” is greater than  “AVGO share received"

### ISSUE THREAD

**Issue by sreenivasmrpivot** [hickeng/financial#119]
“Shares (FMV)” is greater than 
“AVGO share received”.

Does it mean I accidentally got less AVGO?

I verified “Shares (FMV)” formulae and data more than 10 times and they seem to be perfect.

<img width="1229" alt="Screenshot 2024-03-21 at 6 31 35 AM" src="https://github.com/hickeng/financial/assets/26660575/2b8f21b5-c009-466e-aaa3-fb565afb7fd8">

**Comment by hickeng** [comment]
The "Shares (FMV)" value should match the total number of AVGO you were awarded, yes.
I don't see any way for these to be different other than a data entry error unless your transaction log is internally inconsistent. The validation is there as a sanity check against data entry errors.

I recommend you enter the `AVGO qty from eTrade` values and see which ones highlight as different vs the calculated lot amounts.

I recommend you double check the quantity of VMW shares you entered into the ESPP and RSU sheets as that, combined with the inputs in `Summary!B25` and `Summary!B26` is the data used to generate that `Shares (FMV)` value.

If all your data entry looks correct, you can DM me specific figures and we can work through it.

**Comment by sreenivasmrpivot** [comment]
Thanks a lot @hickeng  I will verify again and DM you. I appreciate your kind help.

**Comment by sreenivasmrpivot** [comment]
@hickeng  I verified again and there still seems to be mismatch. Let me know a time when we can work together on this.

**Comment by sreenivasmrpivot** [comment]
@hickeng  I finally resolved in the mismatch between "Shares (FMV)” and “AVGO share received" . Now they match.
Choosing "Per-lot - from strategy or manual selection" for "Cash/stock ratio" in the Summary sheet fixed the mismatch.

However I do not understand how to use the other values in the screenshot section.

Any documentation guidance to choose the right options here will be helpful.

<img width="997" alt="Screenshot 2024-03-24 at 10 15 37 AM" src="https://github.com/hickeng/financial/assets/26660575/5671cc8a-8966-4ed8-89db-55a40959d443">

**Comment by hickeng** [comment]
Worked through this via DM - this relates to inconsistencies in the input data from eTrade. @sreenivasmrpivot will follow up with customer service to correct.
