### ISSUE TITLE
Form 8949 instructions prohibit changing column (d), but your TurboTax instructions say to change it?

### ISSUE THREAD

**Issue by cfryanr** [hickeng/financial#122]
Hi, thanks so much for developing and sharing this project! It is very helpful!

I noticed that the [instructions for Form 8949](https://www.irs.gov/pub/irs-pdf/i8949.pdf) say:

> If you receive Forms 1099-B or 1099-S (or substitute statements), always report the proceeds (sales price) shown on the form (or statement) in column (d) of Form 8949. If Form 1099-B (or substitute statement) shows that the cost or other basis was reported to the IRS, always report the basis shown on that form (or statement) in column (e). If any correction or adjustment to these amounts is needed, make it in column (g).

But your Turbo Tax entry instructions say to override these amounts. Those overrides eventually appear in the Form 8949 generated by Turbo Tax.

I'm curious how you came to the conclusion that you should cause column (d) and column (e) to be different from what is shown on Form 1099-B? Could you cite your sources used to come to that decision? That would be very helpful.

**Comment by hickeng** [comment]
I've noted my reasoning and the sources for doing so in the doc [here](https://github.com/hickeng/financial/blob/main/usage.md#form-8949).

I'm going to be releasing 0.1.7 today, which allows you to switch between the two described behaviours. The excel version might lag the release a little as it's proving more problematic this time.

**Comment by cfryanr** [comment]
Thanks, that's fantastic!

**Comment by hickeng** [comment]
Closed with 76a0079c69c334bf6e1d34919b864a95d9d5bd01
