### ISSUE TITLE
Clarify usage of `Code (f)` in form 8949

### ISSUE THREAD

**Issue by shashankram** [hickeng/financial#132]
The [8949 section](https://github.com/hickeng/financial/blob/main/usage.md#form-8949) mentions
```
The values in the sheet are those needed to go into Form 8949 (although the Code (f) is currently missing). However most people will be using tax prep software, so are more likely to want to use those values to correct an imported 1099-B
```

What is the guidance on this if one is not using a tax prep software but providing details in the sheet to their CPA? Is `Code (f)` column required in that case?

Please advise, thanks.

**Comment by hickeng** [comment]
I think you're looking at an older version of the repo - that quote is from 0.1.6 documentation and earlier. The `Code (f)` column is correctly populated.

If providing values to your CPA, they should be well aware of the codes that are necessary in Form8949 when providing adjusted values. They software _they_ use probably generates those codes automatically when providing values that differ from the corresponding 1099-B.

I'd give your CPA the generated Form8949 numbers (see [here](https://github.com/hickeng/financial/blob/main/usage.md#form-8949) for how to collate those) and let them transcribe those into whatever software they use.

You could ask them whether the need Form8949 with combined or cash-only proceeds... or just supply both. See the doc linked above for how to change between the Form8949 display style.
