### ISSUE TITLE
Is this the right way to think about the cost basis (it isn't zero) for the cash component?

### ISSUE THREAD

**Issue by ps3btc** [hickeng/financial#134]
Is this the right way to think about the cost basis (it isn't zero) for the cash component?

https://docs.google.com/spreadsheets/d/19MNip_tRXk7Z7qucGdSIJf4V79HwH3_L8vILMAVG7XQ/edit#gid=0

When I run your script I get a cost basis of $0 for the cash component but in the spreadsheet above I estimate it in Row 11? Does that look right? If it doesn't why not? Thanks in advance!!

**Comment by hickeng** [comment]
[This document](https://github.com/hickeng/financial/blob/main/documents/Broadcom%20-%20Form%208937%20Acquistion%20of%20VMware%20Inc..pdf) describes the tax impact to shareholders of the merger. It's distilled from the Merger Agreement and is a standard IRS form for describing the impact to tax basis.

What you've got in the spreadsheet _massively_ underestimates tax. You're using the basis from VMW shares to offset the cash gain, and you're claiming that your basis in AVGO is the FMV at the time they were assigned... despite paying no money for them, or tax on them.

It may be useful to consider that in exchange for 1 share of VMW, you received $196.86 true economic compensation:
* $68.2575 cash
* 0.131292 AVGO (value of $128.60)

In your example, that's $19,685.80 with a basis of $9,000, so you've got $10,685.80 of gain to pay tax on. So if you have a cost basis of 0 for the cash, you're deferring tax on $3859.80 to the future.

Put one of your RSU lots into the sheet linked from this repo, set the `Display of Form 8949` value to `Cash & AVGO FMV`, then look at the F8949 section for the lot. It will show the true economic compensation as the Proceeds, and the true Basis. It might help understand the actual compensation involved.
