### ISSUE TITLE
When is the final 1.0 release expected? 

### ISSUE THREAD

**Issue by shashankram** [hickeng/financial#135]
Hi, I am waiting to file my tax returns based on the 1.0 release of this project. When is that expected to cut? Are there any known problems with 0.1.7 version that one needs to be aware of?

Thanks

**Comment by hickeng** [comment]
The remaining known issues are mechanical ones that don't impact the numbers.

I'll likely tag 1.0 at the weekend - it'll be the one that I use for filing.
