### ISSUE TITLE
ESPP Form8949 adjustment cash only option

### ISSUE THREAD

**Issue by codernet** [hickeng/financial#136]
In ESPP sheet, Form8949, adjustment (g), for "cash only" option, should the value equal to "gain - proceeds" instead of "proceeds - gain" ? Thanks.

`=LET(
proceedsStyle,Reference!$E$9,
proceeds,AS8,
gain,AW8,
numVmwShares,D8, 
vmwBasis, AD8, 
avgoQty,AI8, 
avgoFMV,Reference!$B$18, 
cashReceived,AA8, 
avgoTotalValue, avgoFMV*avgoQty, 
vmwTotalBasis, vmwBasis*numVmwShares,
alternateGainAmount,AJ8, 
basis1099B, AT8,
SWITCH(proceedsStyle,
  "cashOnly",
    proceeds - gain,
  "combined",
    basis1099B - IF(cashReceived<alternateGainAmount,
      avgoTotalValue,
      vmwTotalBasis
  )
))`

**Comment by hickeng** [comment]
You're correct - should be `gain - proceeds + basis1099B` for cash only (basis1099B will be 0 by IRS rules... but should have it for correctness).

Luckily there are no ESPP lots that have a basis over 128.60 (alternate gain calc threshold) so none of them should have a non-zero adjustment with `Cash Only` which means the result of both incorrect and correct calc will be zero.
