### ISSUE TITLE
ESPP 8949 Adjustment(g) shows 0 when display option is set to `cash only`

### ISSUE THREAD

**Issue by shashankram** [hickeng/financial#137]
When I switch the 8949 display option to `cash only`, the `Adjustment(g)` values are zero, thereby considering all the proceeds as gains. This does not seem correct?

![image](https://github.com/hickeng/financial/assets/21697719/85c7d28a-3e6f-41e2-99c1-2274845b5417)

**Comment by hickeng** [comment]
This is correct for lots where the cash received is less than the alternate gain calculation. Note that the `Gain (h)` value remains the same between the two settings. The Gain for a lot is dictated by the formula in Form8937.

See my comment [here](https://github.com/hickeng/financial/issues/134#issuecomment-2032629332) for some additional explanation as to why.

**Comment by shashankram** [comment]
Thanks @hickeng. Does that mean I do not need to provide any adjustment for such lots? Or is there additional info I need to provide to my CPA when using the `Cash only` option?

**Comment by hickeng** [comment]
Give your CPA all of the generated Form8949 numbers, regardless of adjustment(ESPP) or basis(RSU) being zero.

If all of your lots have a zero basis and adjustment then you can just use the 1099 as-is without correction. It's unlikely to be the case given the way basis was spread, but could happen.

**Comment by shashankram** [comment]
All of my ESPP lots have a 0 adjustment with the `cash only` option, but some RSU slots have the basis generated.

**Comment by hickeng** [comment]
That's expected for ESPP. Once you factor in the 15% discount, none of the ESPP lots got close to a high enough basis (128.60) for the alternate gain calc to apply. The highest basis ESPP ever had (for my grant/purchase dates anyway) was `120.22` from 2019-08-31 purchase, and that was adjusted down to `103.64` by the 2021 dividend.

**Comment by shashankram** [comment]
Does that mean we do not need to provide any basis adjustments for the 1099-B provided by Etrade?

**Comment by hickeng** [comment]
> Does that mean we do not need to provide any basis adjustments for the 1099-B provided by Etrade?

Correct, for the lots that don't have a non-zero basis, which is all the ESPPs.

For ESPP the complexity is the future basis factoring in the imputed ordinary income.
