### ISSUE TITLE
Should the basis adjustment be 0 if past special dividend were handled incorrectly?

### ISSUE THREAD

**Issue by sahilvv** [hickeng/financial#140]
The 2 special dividend received in 2018 and 2021 were handled as ordinary dividend on my tax return. In this case should I set the basis adjustment of 10.18 and 16.58 to 0 to reflect the cost basis accordingly?

**Comment by hickeng** [comment]
You should probably talk to a CPA about how to go about this.

If you were with eTrade I'd also double check that your conclusion is correct as no one else has reported this type of error. The 2018 and 2021 dividends had two parts to them:
* taxable dividend
* untaxed return of capital

so to be sure you didn't receive any of the distribution as return of capital, you'd need to check whether the value reported as dividend is the entire amount for both those years, not just whether there's some dividend amount. The Form 8937s for the distributions in the repo have the breakdown of the dividend vs RoC amounts.

Simplest way to do this is probably to check the dollar value you received as a deposit vs the dividend amount on your filed taxes but you could also go from the number of shares you held, and use the specific part values to calculated expected dividend vs RoC amounts.

From a mechanical perspective, setting the return of capital values for the distributions in the Reference sheet to 0 will do what you're asking.
