### ISSUE TITLE
Clarify "Factional share value" dropdown in Summary sheet

### ISSUE THREAD

**Issue by shashankram** [hickeng/financial#144]
The `Factional share value` provides 3 options:
- etrade
- custom
- form 8937

I can't find the guidance regarding this dropdown. In my case, I retrieved the fractional share from the 1099-B. Does that mean I should select `custom` here?

Thanks

**Comment by hickeng** [comment]
I've added a note into the sheet for the cell.

You should use "eTrade" - everyone should use eTrade.

The other options are there to explore the impact of eTrade's delay in selling the fractional share, but "eTrade" is the value at which it was _actualy_ sold.
