### ISSUE TITLE
Add a sheet for stocks held in etrade individual account

### ISSUE THREAD

**Issue by pushkar00** [hickeng/financial#147]
In my case, I had a combination  ESPP, RSU and VMW stocks held in individual brokerage account in Etrade which were purchased after market with cash probably during 2016. 

In the conversion  process, Etrade added all of the stocks and exchanged the total value for combination of AVGO, cash and fractional. The transaction log shows this total in Etrade. Since the sheet is missing this value, it highlights validation errors on the summary page. 

Could we add a new sheet for such individual stocks purchased outside of ESPP and RSU.

**Comment by hickeng** [comment]
I recommend simply adding them to the RSU sheet. From a calculation standpoint RSUs are indistinguishable from regular shares held in a non-stock plan account.

Use the date of purchase for the share as the Release Date and override the Market Value pulled from the reference sheet as it's unlikely you got the same price as an RSU vest for that date. Everything else remains the same.
