### ISSUE TITLE
Make spreadsheet compatible with the OpenDocument Spreadsheet Document Format 

### ISSUE THREAD

**Issue by josb** [hickeng/financial#151]
See https://www.loc.gov/preservation/digital/formats/fdd/fdd000439.shtml.

**Comment by hickeng** [comment]
Have you tried doing `File->Download->Open Document` from the Google Sheet? 

I'm not that hopeful given the Excel format download isn't particularly compatible with Excel and requires substantial effort to fix up.

Given most CPAs are wanting Excel format if they cannot use a Google Sheet I'm unlikely to add the pain of another manual format conversion to every release.

**Comment by josb** [comment]
That's one of the problems with closed, proprietary standards which is why I was suggesting this - simply publish a `.ods` file here with each release so everybody stands a chance to be able to read it properly.

Nevertheless, thanks for your efforts, George!

**Comment by hickeng** [comment]
Unfortunately there's no "simply" about it. Perhaps if I'd started offline, not using Google Sheets, and not wanting to be able to write scripts against the sheet this would have been viable.

If you want to export as ODS and go through the exercise of fixing up the various compatibility issues I'll happily add a link to an ODS version of 0.1.8 to the release.

If I was doing this again I'd probably not use a spreadsheet at all. Instead I'd write it as a service hosted somewhere that can render a sheet, with calculations, from various inputs.

**Comment by josb** [comment]
Understood. I wasn't aware of your scripting requirement, and I agree with your idea to not use a spreadsheet at all here.
As an example, https://github.com/wligithub/tax-tool uses Python.
Again, this is a great service your provided to a lot people, much appreciated. 🙏🏻

**Comment by josb** [comment]
That makes sense, thanks George.
