### ISSUE TITLE
How to calculate the gains from the sale of AVGO shares?

### ISSUE THREAD

**Issue by shashankram** [hickeng/financial#157]
I am unsure what the columns `AVGO tax-basis per share` and `Potential Captial Gain (AVGO)` imply. For a given lot, how do I calculate the impact on taxes for selling just a part of the lot?

Thanks

**Comment by hickeng** [comment]
`AVGO tax-basis per share` - after you've paid 2023 taxes incurred by the merger (assuming you used one of the approaches the sheet provides) this is the tax basis for AVGO shares in the lot. You would enter this value, multiplied by the number of shares sold from the lot, as the cost-basis for the sale in Turbotax or similar when filing 2024 taxes.

The `Potential Captial Gain (AVGO)` is an estimate of your capital gain (`Sale Proceeds` - `Tax Basis`) from selling the entire lot. It's there to provide an indication of pending profit, and therefore tax liability, to help select which lots to sell from.

You precise tax impact is impossible to calculate without a lot more info as CGT percentage is variable based on annual income thresholds. 20% is your worst case for federal captial gain taxes, and if you're in CA then capital gains are taxed at your marginal tax rate, so 12-13% worst case.

Assuming you've got some idea of where your annual income will fall and therefore what state and federal rates you'll incur use:
```
capital gain from lot = proceeds from lot - (number of shares sold from lot * AVGO tax-basis per share)

# assume 20% tax rate
federal tax liability from lot = 0.2 * capital gain from lot
# assume California and maximum tax threshold of 13%
state tax liability from lot = 0.13 * capital gain from lot
```

If you've got any capital losses, from 2024 or carried over from prior years, you deduct those from the capital gain before calculating tax.

**Comment by shashankram** [comment]
Thanks @hickeng. Could you also clarify `AVGO basis adjusted by Ordinary Income` and `Pending Ordinary Income` in the ESPP sheet and its implication on tax reporting?

**Comment by hickeng** [comment]
> Thanks @hickeng. Could you also clarify `AVGO basis adjusted by Ordinary Income` and `Pending Ordinary Income` in the ESPP sheet and its implication on tax reporting?

See this section https://github.com/hickeng/financial/blob/main/usage.md#reporting-the-imputed-ordinary-income-from-espp-sale

When you pay tax on the ordinary income, that tax adjusts the tax basis of the shares so I provided that adjusted basis for use on sale of the shares.
The Pending Ordinary Income is the amount you need to declare as regular income, resulting from the ESPP discount, when you sell. You'll need to divide that by the number of shares in the lot to get the per-share value, then multiply by the number of shares you sold from the lot.
