### ISSUE TITLE
Implication for residents of states with no state tax on Summary sheet

### ISSUE THREAD

**Issue by sreenivasmrpivot** [hickeng/financial#95]
What is the total taxes owed for residents from states where there is no state tax? I assume, such people should be focussed only on the "Federal data" in the Summary sheet. Is there a way to pick the state or at least enter or check a box saying my state does not have state tax and the state tax liability to show up as 0?

<img width="1199" alt="Screenshot 2024-03-10 at 8 12 32 PM" src="https://github.com/hickeng/financial/assets/26660575/34aa5a00-32eb-44fa-b4ab-5ce0a1364731">

**Comment by hickeng** [comment]
See https://github.com/hickeng/financial/issues/20 tracking support for states other than CA.

You are correct - just ignore the state taxes. As of v0.1.5 your best option if you want this to omit state taxes from the estimate, is to adjust the state tax thresholds in Reference or just set `Reference!B60` to 0 explicitly.

The estimate is just that and has no sophistication - it's intent is for rough ballpark figures to determine if you've met safe harbor thresholds. If you don't have state tax then you presumably don't need to care about State thresolds.

FreeTaxeUSA, TurboTax, et al are going to give you accurate tax estimates as they'll actually run the numbers through the IRS workbooks.

Closing as a dup - if you want to continue discussion for specific changes I recommend doing so in #20.
